"""add new columns

Revision ID: c1d4af97650a
Revises: eee2f0cd7cd7
Create Date: 2026-03-12 09:55:31.916279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d4af97650a'
down_revision = 'eee2f0cd7cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key('fk_question_topic', 'topic', ['topic_id'], ['topic_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_topic', type_='foreignkey')
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
