"""Add image and question type support

Revision ID: e77bfb7929f2
Revises: c1d4af97650a
Create Date: 2026-03-16 13:41:03.031343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77bfb7929f2'
down_revision = 'c1d4af97650a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('question_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('option_a',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('option_b',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('option_c',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('option_d',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('topic_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('topic_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('option_d',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('option_c',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('option_b',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('option_a',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('question_type')
        batch_op.drop_column('question_image')

    # ### end Alembic commands ###
