"""Add foreign key for subject_id in ExamResult

Revision ID: eee2f0cd7cd7
Revises: 
Create Date: 2026-03-10 09:15:15.471203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee2f0cd7cd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_result', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_examresult_subject', 'subject', ['subject_id'], ['subject_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_result', schema=None) as batch_op:
        batch_op.drop_constraint('fk_examresult_subject', type_='foreignkey')

    # ### end Alembic commands ###
